# Config file copied from https://github.com/flycheck/emacs-travis
language: emacs-lisp
env:
  - EMACS_VERSION=emacs-24.3-travis
  - EMACS_VERSION=emacs-24.5-travis
  - EMACS_VERSION=emacs-25.3-travis
  - EMACS_VERSION=emacs-26.1-travis
  - EMACS_VERSION=emacs-git-snapshot-travis
before_install:
  - export PATH="/home/travis/.evm/bin:/home/travis/.cask/bin:$PATH"
  - git clone https://github.com/rejeep/evm.git /home/travis/.evm
  - evm config path /tmp
  - evm install $EMACS_VERSION --use || true
  - curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
install:
  # Install your dependencies
  - cask install
script:
  # Run your tests
  - make test
